CREATE_USER_TABLE = '''
CREATE TABLE IF NOT EXISTS USERS
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USERNAME TEXT,
FIRST_NAME TEXT,
LAST_NAME TEXT,
UNIQUE (TELEGRAM_ID)


)
'''
CREATE_ANSWER_TABLE = """
CREATE TABLE IF NOT EXISTS User_Answers
(
ID INTEGER PRIMARY KEY,
ANSWERS TEXT,
)"""
INSERT_USER = '''
INSERT INTO USERS VALUES (?,?,?,?,?)
'''
INSERT_ANSWER = '''
INSERT INTO Answers (?)'''

